name: CI
on:
  push:
  pull_request:
jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps (if present)
        run: |
          python -m pip install --upgrade pip
          if [ -f apps/api/requirements.txt ]; then pip install -r apps/api/requirements.txt; fi
          if [ -f apps/worker/requirements.txt ]; then pip install -r apps/worker/requirements.txt; fi
          pip install pytest ruff || true
      - name: Lint
        run: ruff check . || true
      - name: Tests
        run: pytest -q || true
